apiVersion: v1
kind: ConfigMap
metadata:
  name: user-api-nginx-config
data:
  nginx.default.conf: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  _;
      root   /var/www/html/public;
      index index.php index.html index.htm;

      location / {
          try_files $uri $uri/ /index.php?$query_string;
      }

      location ~ \.php$ {
          fastcgi_pass 127.0.0.1:9000;
          fastcgi_index index.php;
          fastcgi_buffers 16 16k;
          fastcgi_buffer_size 32k;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          #fixes timeouts
          fastcgi_read_timeout 600;
          include fastcgi_params;
      }

      location ~ /\.ht {
          deny all;
      }

      access_log /dev/stdout;
      error_log /dev/stderr;
    }